# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Place.delete_all
Place.create(:title => "CN Tower", :photo_url => "http://torontodotcomassets.s3.amazonaws.com/wp-content/uploads/2013/02/610919-324776_7-174x116.jpg", :admission_price => 50, :description => "The CN Tower is Toronto’s tallest and most defining landmark. Photos of Toronto are often defined by the building, which stretches more than 550 metres into the sky.\nToday, aside from serving as a hub for telecommunications across the city, the CN Tower has become a major tourist destination. Visitors can test their courage by walking across the glass floor 113 stories above the ground. The first of its kind in the world, the glass floor gives you that dare-to-walk-on-air experience, with only 2.5 inches of glass holding you 342 metres in the air. The glass floor is actually stronger than most commercial floors and has the strength to hold 38,556 kg (85,000 lbs) or 14 hippos! Or, if you dare, travel higher up the tower to the Sky Pod, another 33 storeys above ground.")
Place.create(:title => "Canada’s Wonderland", :photo_url => "http://torontodotcomassets.s3.amazonaws.com/wp-content/uploads/2013/02/723185-424996_31-174x116.jpg", :admission_price => 65, :description => "Canada’s Wonderland is Canada’s first and largest theme park featuring over 200 attractions, 68 thrilling rides, North America’s greatest variety of roller coasters, Splash Works, a 20-acre water park and live shows. At 306 feet (93.27 m) in the air, Leviathan is the tallest ride in the park, dropping riders at an intense 80 degree angle. Across the way, Behemoth has eight extreme drops, open air seating, high speed twists, turns and loops. The daring may want to be lifted 23 stories high and then dropped at 100 kilometres per hour aboard Drop Tower. Not to be outdone are Vortex, Canada’s first suspended roller coaster, an intense corkscrew design in The Bat, Skyrider’s shark curves and side-winding helix (standing up of course), Dragon Fire’s two 360-degree loops, the trek through Wonder Mountain aboard Thunder Run, Windseeker, a 301 ft swing ride, and let’s not forget the coaster that lives up to its name, The Mighty Canadian Minebuster, the largest and longest wooden coaster in Canada.")
Place.create(:title => "Harbourfront Centre", :photo_url => "http://torontodotcomassets.s3.amazonaws.com/wp-content/uploads/2014/01/Harbourfront-Centre-patio-174x116.jpg", :admission_price => 30, :description => "Harbourfront Centre is a year-round facility, featuring concerts, dance performances, readings, films and kids’ shows every weekend and many weeknights throughout the year. The centre puts a large emphasis on culturally diverse acts, and the corporate community’s involvement enables an incredible draw of international talent. Harbourfront Centre has several major venues for music, dance and cultural events, in and around two major multi-use buildings. The Queens Quay Terminal houses a wide variety of shops and services. The York Quay Centre houses an art gallery, installations, the Lakeside Terrace, a patio and an information booth. There is also a large pond that doubles as a seasonal, outdoor skating rink.")
Place.create(:title => "Royal Ontario Museum (ROM)", :photo_url => "http://torontodotcomassets.s3.amazonaws.com/wp-content/uploads/2013/02/643390-357337_31-174x116.jpg", :admission_price => 40, :description => "Generations of children and adults have trooped through the museum since it first opened in 1914. With six million objects in its collections and 40 galleries of art, archaeology and natural science, the ROM offers a whole world to explore. Four giant carved totem poles rise in the centre of the stairwells; the largest is 24.5 metres (over 80 ft.) tall. The hands-on Biodiversity gallery offers families a fun interactive experience about the interdependence of people, animals and plants. The dramatic Michael Lee-Chin Crystal expansion houses six permanent collection galleries that feature many objects never before displayed, along with some old favourites. They include dinosaurs and mammals, the cultures of South and Central Asia, Africa, the American continents, the Asia-Pacific region (including Oceania) along with textiles and costumes from around the world.")
Place.create(:title => "Medieval Times Toronto", :photo_url => "http://torontodotcomassets.s3.amazonaws.com/wp-content/uploads/2013/03/391132_10150993591595048_1262466797_n-174x116.jpg", :admission_price => 30, :description => "Medieval Times Dinner & Tournament is a living link to the past where the glory, chivalry and valor of old burst to life in authentic tournament action. While guests enjoy a four-course banquet served medieval style, six brave knights compete in games of skill astride magnificent Andalusian stallions. Lances splinter against steel shields, broad swords spark and a champion emerges, to the cheers of the enthusiastic crowd. The spectacle unfolds nightly inside a fully enclosed European-style castle. Surprisingly odorless, (due to the crushed granite on which the action takes place), the Grand Ceremonial Arena offers seating for up to 1,400 guests. The Knight Club, offering full bar service, comes to life each evening after the final performance giving guests the opportunity to meet the show cast, take pictures, get autographs and dance to selections from the medieval jukebox. Other features include a medieval-themed Convention Hall available for all types of corporate, school, team and special events. Vegetarian, Halal and Kosher meals available.")
Place.create(:title => "Black Creek Pioneer Village", :photo_url => "http://torontodotcomassets.s3.amazonaws.com/wp-content/uploads/2015/05/blackcreek-174x116.jpg", :admission_price => 20, :description => "A visit to Black Creek Pioneer Village is a step back in time to 19th-century Ontario. Forty authentically restored homes, workshops, public buildings and farms recreate the atmosphere of life in a rural Victorian community of the 1860s. Craftspeople and workers wearing period costumes demonstrate skills such as open-hearth cooking, bread-making, looming, milling, blacksmithing, sewing, printing and more. The Event Pavilion opens its doors to a host of possibilities for Black Creek Pioneer Village. The covered pavilion includes a stage, seating for up to 300 people and a snack bar. In the past it was home to the Métis Arts Festival and the Celtic Sounds Festival. The Bolton Shop showcases the history of photography and techniques used in the 1860s in a 19th century studio. The studio has family-friendly activities and the opportunity to strike a pose.")